[build]
publish = "."

[redirects]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  basePath = "https://ahmad-abdullah-ahmad-portfolio.netlify.app"
  exclude = ["/404"]
  changeFreq = "daily"
  priority = 0.7
  autoUpdate = true

[dev]
  framework = "#static"
  targetPort = 3000
  publish = "."

[functions]
directory = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add your custom domain here
domain = "ahmad-abdullah-ahmad-portfolio.netlify.app"
